// Selected works checked against primary sources on 2026-09-17.
// Keep venue labels explicit: an arXiv preprint is not a peer-reviewed venue.
export const publications = [
  {
    id: 'a2gc',
    title: 'A2GC: Asymmetric Aggregation with Geometric Constraints for Locally Aggregated Descriptors',
    authors: ['Zhenyu Li', 'Tianyi Shang'],
    venue: 'CVPR',
    year: 2026,
    topic: 'vision',
    paperUrl: 'https://openaccess.thecvf.com/content/CVPR2026/html/Li_A2GC_Asymmetric_Aggregation_with_Geometric_Constraints_for_Locally_Aggregated_Descriptors_CVPR_2026_paper.html',
    codeUrl: 'https://github.com/CV4RA/A2GC',
    bibtex: `@inproceedings{li2026a2gc,
  author = {Li, Zhenyu and Shang, Tianyi},
  title = {{A2GC}: Asymmetric Aggregation with Geometric Constraints for Locally Aggregated Descriptors},
  booktitle = {Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)},
  year = {2026},
  month = {June},
  pages = {19423--19431},
  url = {https://openaccess.thecvf.com/content/CVPR2026/html/Li_A2GC_Asymmetric_Aggregation_with_Geometric_Constraints_for_Locally_Aggregated_Descriptors_CVPR_2026_paper.html}
}`,
    summary: {
      en: 'Spatially aware visual place recognition through asymmetric feature aggregation and geometric constraints.',
      zh: '融合非对称特征聚合与几何约束，探索具有空间感知能力的视觉地点识别。',
    },
  },
  {
    id: 'symploc',
    title: 'Riemannian and Symplectic Geometry for Hierarchical Text-Driven Place Recognition',
    authors: ['Tianyi Shang', 'Zhenyu Li'],
    venue: 'arXiv preprint',
    year: 2026,
    topic: 'navigation',
    paperUrl: 'https://arxiv.org/abs/2604.01598',
    bibtex: `@misc{shang2026symploc,
  author = {Shang, Tianyi and Li, Zhenyu},
  title = {Riemannian and Symplectic Geometry for Hierarchical Text-Driven Place Recognition},
  year = {2026},
  eprint = {2604.01598},
  archivePrefix = {arXiv},
  primaryClass = {cs.CV},
  url = {https://arxiv.org/abs/2604.01598}
}`,
    summary: {
      en: 'Aligning language and 3D scenes at the instance, relation, and global levels for robot localization.',
      zh: '在实例、关系与全局三个层次对齐语言与三维场景，服务于机器人定位。',
    },
  },
  {
    id: 'spatialoc',
    title: 'SpatiaLoc: Leveraging Multi-Level Spatial Enhanced Descriptors for Cross-Modal Localization',
    authors: ['Tianyi Shang', 'Pengjie Xu', 'Zhaojun Deng', 'Zhenyu Li', 'Zhicong Chen', 'Lijun Wu'],
    venue: 'arXiv preprint',
    year: 2026,
    topic: 'navigation',
    paperUrl: 'https://arxiv.org/abs/2601.03579',
    bibtex: `@misc{shang2026spatialoc,
  author = {Shang, Tianyi and Xu, Pengjie and Deng, Zhaojun and Li, Zhenyu and Chen, Zhicong and Wu, Lijun},
  title = {{SpatiaLoc}: Leveraging Multi-Level Spatial Enhanced Descriptors for Cross-Modal Localization},
  year = {2026},
  eprint = {2601.03579},
  archivePrefix = {arXiv},
  primaryClass = {cs.CV},
  url = {https://arxiv.org/abs/2601.03579}
}`,
    summary: {
      en: 'Connecting natural language with point clouds using spatial relationships and uncertainty-aware localization.',
      zh: '利用空间关系和不确定性感知定位，将自然语言描述与点云场景连接起来。',
    },
  },
  {
    id: 'mambaplace',
    title: 'MambaPlace: Text-to-Point-Cloud Cross-Modal Place Recognition with Attention Mamba Mechanisms',
    authors: ['Tianyi Shang', 'Zhenyu Li', 'Pengjie Xu', 'Jinwei Qiao'],
    venue: 'IROS',
    year: 2025,
    topic: 'navigation',
    paperUrl: 'https://arxiv.org/abs/2408.15740',
    bibtex: `@inproceedings{shang2025mambaplace,
  author = {Shang, Tianyi and Li, Zhenyu and Xu, Pengjie and Qiao, Jinwei},
  title = {{MambaPlace}: Text-to-Point-Cloud Cross-Modal Place Recognition with Attention Mamba Mechanisms},
  booktitle = {2025 IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)},
  year = {2025},
  url = {https://ieeexplore.ieee.org/document/11246747}
}`,
    summary: {
      en: 'A coarse-to-fine framework that brings text and 3D point clouds together through attention Mamba mechanisms.',
      zh: '通过注意力 Mamba 机制连接文本与三维点云，实现由粗到细的跨模态地点识别。',
    },
  },
  {
    id: 'text4vpr',
    title: 'Bridging Text and Vision: A Multi-View Text-Vision Registration Approach for Cross-Modal Place Recognition',
    authors: ['Tianyi Shang', 'Zhenyu Li', 'Pengjie Xu', 'Jinwei Qiao', 'Gang Chen', 'Zihan Ruan', 'Weijun Hu'],
    venue: 'IROS',
    year: 2025,
    topic: 'navigation',
    paperUrl: 'https://arxiv.org/abs/2502.14195',
    bibtex: `@inproceedings{shang2025text4vpr,
  author = {Shang, Tianyi and Li, Zhenyu and Xu, Pengjie and Qiao, Jinwei and Chen, Gang and Ruan, Zihan and Hu, Weijun},
  title = {Bridging Text and Vision: A Multi-View Text-Vision Registration Approach for Cross-Modal Place Recognition},
  booktitle = {2025 IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)},
  year = {2025},
  url = {https://ieeexplore.ieee.org/document/11246871}
}`,
    summary: {
      en: 'Text4VPR explores place recognition from natural language by matching descriptions to multiple views of a location.',
      zh: 'Text4VPR 将自然语言描述与地点的多视角图像匹配，探索由文字出发的地点识别。',
    },
  },
];
